### ISSUE TITLE
Get window name from ProcessID in all sessions

### ISSUE THREAD

**Issue by mlukac89** [danports/cassia#87]
Hi, is it possible to get window name from ProcessID in all sessions from this Package ?

**Comment by mlukac89** [comment]
I tried like this, but still can't get window title only handle
         `List<int> procs = new List<int>(); // list to insert all PID's

            ITerminalServer server = manager.GetLocalServer(); // get server name
            foreach (ITerminalServicesProcess process in processes)
            {
                foreach (ITerminalServicesSession session in server.GetSessions())
                {
                    if (process.ProcessName == "terminal.exe" && session.SessionId == process.SessionId)
                    {
                        int ssid = process.SessionId;
                        int pid = process.ProcessId;
                        string pname = process.ProcessName;

                        procs.Add(pid); // add each PID to list

                        //WriteProcessInfo(process);
                        Console.WriteLine("Session ID: {0} PID: {1} Name: {2}", ssid, pid, pname);
                        count += 1;
                    }
                }
            }
            Console.WriteLine($"Number of terminal.exe {count.Count()}");


            foreach (var p in procs) // p returns only PID of each process
            {
                var ppname = Process.GetProcessById(p).ProcessName; // process name

                Process[] lname = Process.GetProcessesByName(ppname);

                foreach (Process s in lname)
                {
                    // s.MainWindowTitle  Returns empty string
                    Console.WriteLine("PID: {0} , Name: {1}, Name again {2}", p, ppname, s.MainWindowTitle);
                }
                
     
            }`

**Comment by danports** [comment]
`ITerminalServicesProcess.UnderlyingProcess.MainWindowTitle` should do the trick - this code works for me:
```c#
foreach (var process in new TerminalServicesManager().GetLocalServer().GetProcesses())
    Console.WriteLine($"Session ID: {process.SessionId} PID: {process.ProcessId} Name: {process.ProcessName} Window Title: {process.UnderlyingProcess.MainWindowTitle}");
```
Note also that not all processes expose their main window title in this fashion.
