### ISSUE TITLE
Question: Is it possible to detect disconnects?

### ISSUE THREAD

**Issue by wexman** [danports/cassia#89]
Hi, I would like to do the following:
When my app is running in a rdp session, and that session gets disconnected, I would like to terminate my app.
Is that possible using cassia?

**Comment by danports** [comment]
Actually, you don't need Cassia for this scenario; see [SystemEvents.SessionSwitch](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.sessionswitch?view=netframework-4.8).
