### ISSUE TITLE
total time (dis)connected?

### ISSUE THREAD

**Issue by BrannonKing** [danports/cassia#91]
I see in the session object that there are timestamps for the connect and disconnect events. However, since you can disconnect from a session multiple times, how do I get the total time connected (or disconnected) from a session?

**Comment by danports** [comment]
Unfortunately, I don't believe that the underlying Win32 API tracks or exposes the total time connected for each session (if you can find it in the docs, let me know!). However, you could track this yourself by implementing a Windows service that subscribes to the [SystemEvents.SessionSwitch event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.sessionswitch?view=netframework-4.8).
